#!/usr/bin/env python3
"""Generate the "🐍 Show me the Python" outputs from tools/python_snippets.py.

    python tools/build_python.py            write both files
    python tools/build_python.py --check    fail if either file is out of date (CI)

Outputs:
  site/js/python-snippets.js         loaded by site/js/python-panel.js
  notebooks/try-it-in-python.ipynb   every program, runnable in Google Colab

The notebook is built with the standard library only (plain JSON), so CI
needs nothing installed to run --check.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from python_snippets import SNIPPETS  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
JS_OUT = ROOT / "site" / "js" / "python-snippets.js"
NB_OUT = ROOT / "notebooks" / "try-it-in-python.ipynb"
COLAB = "https://colab.research.google.com/github/YouvenZ/ai-workshop-highschool/blob/main/notebooks/try-it-in-python.ipynb"
SITE = "https://youvenz.github.io/ai-workshop-highschool/play/"


def build_js() -> str:
    data = {s["id"]: {k: s[k] for k in ("emoji", "title", "tagline", "steps", "code") if k in s} | {"pip": s.get("pip")}
            for s in SNIPPETS}
    return (
        "/* GENERATED by tools/build_python.py from tools/python_snippets.py — do not edit by hand. */\n"
        f"window.PY_COLAB = {json.dumps(COLAB)};\n"
        f"window.PY_SNIPPETS = {json.dumps(data, ensure_ascii=False, indent=1)};\n"
    )


def md(text: str) -> dict:
    return {"cell_type": "markdown", "metadata": {}, "source": text.strip("\n").splitlines(keepends=True)}


def code(text: str) -> dict:
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [],
            "source": text.strip("\n").splitlines(keepends=True)}


def build_nb() -> str:
    cells = [md(f"""
# 🐍 Try it in Python — every AI from today's workshop

**Can a computer learn?** · Dr. Rachid Zeghlache

Every activity you played with in the browser, written as a short Python
program. Each one is 10–25 lines, and every line is explained.

**How to use this notebook**

1. Click **File → Save a copy in Drive** (so your changes are kept).
2. Click inside a grey code cell and press **Shift + Enter** to run it.
3. Change something — a number, a word, a layer — and run it again. That's how you learn!

Nothing here needs a webcam: the camera activities use a sample photo instead.

[▶ Play with the activities in your browser]({SITE})
""")]
    for i, s in enumerate(SNIPPETS, 1):
        steps = "  →  ".join(s["steps"])
        cells.append(md(f"""
---
## {i}. {s['emoji']} {s['title']}

*{s['tagline']}*

**{steps}**

[Open the activity in your browser]({SITE}{s['id']}.html)
"""))
        if s.get("pip"):
            cells.append(code(f"%pip install -q {s['pip']}"))
        cells.append(code(s["code"]))
        if s.get("show"):
            cells.append(code((s.get("show_import", "") + "\n" + f"{s['show']}   # show the result here in the notebook").strip()))
    cells.append(md("""
---
## 🎉 That's all of them!

Next steps: change the layers in **Build a Brain**, write your own sentences in
**Mood Reader**, or paste your favourite book into **Mini ChatGPT**.
"""))
    nb = {
        "cells": cells,
        "metadata": {
            "colab": {"provenance": [], "toc_visible": True},
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python"},
        },
        "nbformat": 4, "nbformat_minor": 5,
    }
    for n, c in enumerate(nb["cells"]):
        c["id"] = f"cell-{n:02d}"
    return json.dumps(nb, ensure_ascii=False, indent=1) + "\n"


def main() -> int:
    check = "--check" in sys.argv
    outputs = {JS_OUT: build_js(), NB_OUT: build_nb()}
    stale = []
    for path, text in outputs.items():
        if check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path.relative_to(ROOT))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(ROOT)}")
    if stale:
        print("✗ out of date — run `python tools/build_python.py`:", *stale, sep="\n  ")
        return 1
    if check:
        print(f"✓ {len(SNIPPETS)} Python snippets in sync with the site and the notebook")
    return 0


if __name__ == "__main__":
    sys.exit(main())
